// Copyright (c) 2026 Philippe Vollenweider
//
// This file is part of the GalleryPack commercial platform.
// This source code is proprietary and confidential.
// Use, reproduction, or distribution requires a valid commercial license.
// Unauthorized use is strictly prohibited.

// apps/api/src/services/tusService.js
//
// Builds a tus Server instance for a given gallery.
//
// Upload flow:
//   1. Client sends tus POST (create) with Upload-Metadata: filename, galleryId, userId
//   2. Server stores chunks under internal/tus/<galleryId>/
//   3. On complete (onUploadFinish):
//      a. Move file to private/<slug>/photos/<uuid>.<ext>
//      b. Run Sharp validation + SM thumbnail (same as multer pipeline)
//      c. INSERT into photos table (ON DUPLICATE KEY skips duplicates)
//      d. Enqueue MD thumbnail + prerender
//      e. Extract EXIF async
//      f. Mark gallery needs_rebuild
//
// The completed upload ID is the tus upload ID (UUID generated by @tus/server).
// The photo row ID is derived the same way as the multer flow: UUID = filename without ext.

import path              from 'node:path';
import fs                from 'node:fs';
import { randomUUID }    from 'node:crypto';
import { Server }    from '@tus/server';
import { FileStore } from '@tus/file-store';
import { query }         from '../db/database.js';
import { SRC_ROOT, INTERNAL_ROOT } from '../../../../packages/engine/src/fs.js';
import { runSharp }      from './sharpProcess.js';
import { enqueueSm, enqueueMd, thumbPath, photoThumbnails } from './thumbnailService.js';
import { enqueuePrerender, uploadStarted, uploadFinished }  from './prerenderService.js';
import { extractExif }   from '../../../../packages/engine/src/exif.js';
import { audit, getUploadLinkByToken, getPhotographerByUploadLink } from '../db/helpers.js';
import { emit, EVENTS } from './events.js';
import { uploadLogger as log } from '../lib/logger.js';
import {
  uploadTotal, uploadBytesTotal, uploadDuration, uploadFileSize,
  tusIncompleteUploads,
} from '../lib/metrics.js';

// ── Config ────────────────────────────────────────────────────────────────────

const MAX_FILE_SIZE_BYTES = (Number(process.env.UPLOAD_MAX_SIZE_MB) || 100) * 1024 * 1024;
const MAX_PHOTOS_PER_GALLERY = Number(process.env.GALLERY_MAX_PHOTOS) || 500;
const ALLOWED_EXTS = new Set(['.jpg', '.jpeg', '.png', '.tiff', '.tif', '.heic', '.heif', '.avif']);
const SUPPORTED_FORMATS = 'JPG, PNG, TIFF, HEIC, HEIF, AVIF';

// ── Helpers ───────────────────────────────────────────────────────────────────

function photosDir(slug) {
  return path.join(SRC_ROOT, slug, 'photos');
}

function tusStoreDir() {
  return path.join(INTERNAL_ROOT, 'tus');
}

function decodeMetadata(metadataHeader) {
  if (!metadataHeader) return {};
  const out = {};
  for (const pair of metadataHeader.split(',')) {
    const [key, b64] = pair.trim().split(' ');
    if (key && b64) {
      try { out[key] = Buffer.from(b64, 'base64').toString('utf8'); } catch {}
    }
  }
  return out;
}

// ── Core post-upload pipeline ─────────────────────────────────────────────────
// Called by onUploadFinish. Mirrors the multer pipeline in photos.js exactly.

async function finaliseUpload({ upload, galleryId, userId, studioId, req }) {
  const meta = decodeMetadata(upload.metadata);
  const originalName = meta.filename || meta.name || path.basename(upload.id);
  const ext          = path.extname(originalName).toLowerCase();

  if (!ALLOWED_EXTS.has(ext)) {
    log.warn({ filename: originalName }, 'rejected — unsupported extension');
    return { ok: false, reason: `Unsupported format. Accepted: ${SUPPORTED_FORMATS}` };
  }

  // Resolve gallery slug
  const [gRows] = await query(
    'SELECT id, slug FROM galleries WHERE id = ? AND studio_id = ?',
    [galleryId, studioId],
  );
  const gallery = gRows[0];
  if (!gallery) return { ok: false, reason: 'Gallery not found' };

  // Dedup check: skip if original_name already exists in this gallery
  const [dupRows] = await query(
    'SELECT id FROM photos WHERE gallery_id = ? AND original_name = ? LIMIT 1',
    [gallery.id, originalName],
  );
  if (dupRows[0]) {
    // Already uploaded — clean up tus data file silently
    try { fs.unlinkSync(upload.storage?.path); } catch {}
    return { ok: true, duplicate: true };
  }

  // Gallery quota
  const [countRows] = await query('SELECT COUNT(*) AS n FROM photos WHERE gallery_id = ?', [gallery.id]);
  if (Number(countRows[0].n) >= MAX_PHOTOS_PER_GALLERY) {
    return { ok: false, reason: `Gallery quota exceeded (max ${MAX_PHOTOS_PER_GALLERY} photos)` };
  }

  const destDir  = photosDir(gallery.slug);
  fs.mkdirSync(destDir, { recursive: true });

  // tus stores the completed file at upload.storage.path
  const tusPath  = upload.storage?.path;
  if (!tusPath || !fs.existsSync(tusPath)) {
    return { ok: false, reason: 'Upload data file not found on disk' };
  }

  const photoId  = randomUUID();
  const destName = `${photoId}${ext}`;
  const destPath = path.join(destDir, destName);

  // Move tus completed file → photos directory
  fs.renameSync(tusPath, destPath);

  // Remove tus info file (.json sidecar)
  try { fs.unlinkSync(`${tusPath}.json`); } catch {}

  // Sharp validation + SM thumbnail (same as multer pipeline)
  const smDest = thumbPath(photoId, 'sm');
  const mdDest = thumbPath(photoId, 'md');
  try {
    await runSharp({ op: 'validate-and-thumbs', srcPath: destPath, smPath: smDest, mdPath: mdDest });
  } catch (err) {
    log.error({ filename: originalName, err }, 'Sharp validation failed');
    return { ok: false, reason: `Format non reconnu ou fichier corrompu. Formats supportés : ${SUPPORTED_FORMATS}.` };
  }

  const sizeByte = fs.statSync(destPath).size;

  const [result] = await query(
    `INSERT INTO photos (id, gallery_id, filename, original_name, size_bytes, status, uploaded_by_user_id)
     VALUES (?, ?, ?, ?, ?, 'validated', ?)
     ON DUPLICATE KEY UPDATE size_bytes = VALUES(size_bytes), original_name = VALUES(original_name)`,
    [photoId, gallery.id, destName, originalName, sizeByte, userId],
  );

  if (result.affectedRows === 2) {
    // Race-condition duplicate — clean up
    try { fs.unlinkSync(destPath); } catch {}
    try { fs.unlinkSync(thumbPath(photoId, 'sm')); } catch {}
    try { fs.unlinkSync(thumbPath(photoId, 'md')); } catch {}
    return { ok: true, duplicate: true };
  }

  enqueueSm(destPath, photoId);
  enqueueMd(destPath, photoId);
  enqueuePrerender(destPath, destName);

  extractExif(destPath).then(exif => {
    if (exif && Object.keys(exif).length > 0) {
      query('UPDATE photos SET exif = ? WHERE id = ?', [JSON.stringify(exif), photoId]).catch(() => {});
    }
  }).catch(() => {});

  await query(
    'UPDATE galleries SET needs_rebuild = 1, updated_at = ? WHERE id = ?',
    [Date.now(), gallery.id],
  );

  try { await audit(studioId, userId, 'photo.upload', 'gallery', gallery.id, { filename: destName, via: 'tus' }); } catch {}

  uploadTotal.inc({ status: 'success' });
  uploadBytesTotal.inc({ status: 'success' }, sizeByte);
  uploadFileSize.observe(sizeByte);
  tusIncompleteUploads.dec();

  log.info({ photoId, gallery_id: gallery.id, filename: originalName, size_bytes: sizeByte }, 'upload finished');

  return { ok: true, photoId, file: destName, thumbnail: photoThumbnails(photoId) };
}

// ── Server factory ─────────────────────────────────────────────────────────────
// Returns a tus Server configured for the given studioId.
// Mount at /api/tus — galleryId comes from Upload-Metadata, not the URL.

export function createTusServer(studioId) {
  const datastore = new FileStore({ directory: tusStoreDir() });

  const server = new Server({
    path: '/api/tus',              // used by tus for self-referential Upload-Location URLs
    datastore,
    maxSize: MAX_FILE_SIZE_BYTES,

    // ── onCreate: validate gallery access before accepting any bytes ──────────
    async onUploadCreate(req, res, upload) {
      const meta      = decodeMetadata(upload.metadata);
      const galleryId = meta.galleryId;
      const userId    = req._tusUserId;          // set by auth middleware (see tusMiddleware)

      if (!galleryId) {
        throw { status_code: 400, body: 'Missing galleryId in Upload-Metadata' };
      }

      const [rows] = await query(
        'SELECT id FROM galleries WHERE id = ? AND studio_id = ?',
        [galleryId, studioId],
      );
      if (!rows[0]) {
        throw { status_code: 404, body: 'Gallery not found' };
      }

      // Attach to upload for use in onUploadFinish
      upload._galleryId  = galleryId;
      upload._userId     = userId;
      upload._studioId   = studioId;
      upload._createdAt  = Date.now();

      tusIncompleteUploads.inc();

      return res;
    },

    // ── onUploadFinish: run the full photo pipeline ───────────────────────────
    async onUploadFinish(req, res, upload) {
      uploadStarted();
      const durationS = upload._createdAt ? (Date.now() - upload._createdAt) / 1000 : 0;
      try {
        const meta      = decodeMetadata(upload.metadata);
        const galleryId = meta.galleryId || upload._galleryId;
        const userId    = req._tusUserId  || upload._userId;

        const outcome = await finaliseUpload({
          upload,
          galleryId,
          userId,
          studioId: upload._studioId || studioId,
          req,
        });

        if (!outcome.ok) {
          uploadTotal.inc({ status: 'failed' });
          tusIncompleteUploads.dec();
          throw { status_code: 422, body: outcome.reason };
        }

        if (durationS > 0) uploadDuration.observe(durationS);
      } finally {
        uploadFinished();
      }

      return res;
    },
  });

  return server;
}

// ── Public tus server (upload-link / token flow) ───────────────────────────────
// Token is attached to req._uploadToken by the route middleware before calling server.handle().
// Photos are inserted with status 'approved' and auto-attributed to the linked photographer.

const _publicTusServer = new Map(); // one server (stateless — token validated per-request)

export function getPublicTusServer() {
  const key = '__public__';
  if (!_publicTusServer.has(key)) {
    const datastore = new FileStore({ directory: tusStoreDir() });

    const server = new Server({
      path:     '/upload/tus',
      datastore,
      maxSize:  MAX_FILE_SIZE_BYTES,

      async onUploadCreate(req, res, upload) {
        const token = req._uploadToken;
        if (!token) throw { status_code: 400, body: 'Missing upload token' };

        const link = await getUploadLinkByToken(token);
        if (!link) throw { status_code: 401, body: 'Invalid or expired upload link' };

        upload._link = link;
        return res;
      },

      async onUploadFinish(req, res, upload) {
        const link = upload._link;
        if (!link) throw { status_code: 401, body: 'Invalid or expired upload link' };

        uploadStarted();
        try {
          const meta         = decodeMetadata(upload.metadata);
          const originalName = meta.filename || meta.name || path.basename(upload.id);
          const ext          = path.extname(originalName).toLowerCase();

          if (!ALLOWED_EXTS.has(ext)) {
            throw { status_code: 422, body: `Unsupported format. Accepted: ${SUPPORTED_FORMATS}` };
          }

          // Dedup check
          const [dupRows] = await query(
            'SELECT id FROM photos WHERE gallery_id = ? AND original_name = ? LIMIT 1',
            [link.gallery_id, originalName],
          );
          if (dupRows[0]) {
            try { fs.unlinkSync(upload.storage?.path); } catch {}
            return res;
          }

          // Quota
          const [countRows] = await query('SELECT COUNT(*) AS n FROM photos WHERE gallery_id = ?', [link.gallery_id]);
          if (Number(countRows[0].n) >= MAX_PHOTOS_PER_GALLERY) {
            throw { status_code: 422, body: `Gallery quota exceeded (max ${MAX_PHOTOS_PER_GALLERY} photos)` };
          }

          const destDir  = photosDir(link.gallery_slug);
          fs.mkdirSync(destDir, { recursive: true });

          const tusPath = upload.storage?.path;
          if (!tusPath || !fs.existsSync(tusPath)) {
            throw { status_code: 500, body: 'Upload data file not found' };
          }

          const photoId  = randomUUID();
          const destName = `${photoId}${ext}`;
          const destPath = path.join(destDir, destName);

          fs.renameSync(tusPath, destPath);
          try { fs.unlinkSync(`${tusPath}.json`); } catch {}

          const smDest = thumbPath(photoId, 'sm');
          const mdDest = thumbPath(photoId, 'md');
          try {
            await runSharp({ op: 'validate-and-thumbs', srcPath: destPath, smPath: smDest, mdPath: mdDest });
          } catch (err) {
            log.error({ filename: originalName, err }, 'Sharp validation failed (public)');
            throw { status_code: 422, body: `Format non reconnu. Formats supportés : ${SUPPORTED_FORMATS}.` };
          }

          const photographer = await getPhotographerByUploadLink(link.id);
          const sizeByte     = fs.statSync(destPath).size;

          const [result] = await query(
            `INSERT INTO photos (id, gallery_id, filename, original_name, size_bytes, status, upload_link_id, photographer_id)
             VALUES (?, ?, ?, ?, ?, 'approved', ?, ?)
             ON DUPLICATE KEY UPDATE
               size_bytes = VALUES(size_bytes),
               original_name = VALUES(original_name),
               photographer_id = VALUES(photographer_id)`,
            [photoId, link.gallery_id, destName, originalName, sizeByte, link.id, photographer?.id ?? null],
          );

          if (result.affectedRows === 2) {
            try { fs.unlinkSync(destPath); } catch {}
            try { fs.unlinkSync(thumbPath(photoId, 'sm')); } catch {}
            try { fs.unlinkSync(thumbPath(photoId, 'md')); } catch {}
            return res;
          }

          enqueueSm(destPath, photoId);
          enqueueMd(destPath, photoId);
          enqueuePrerender(destPath, destName);

          extractExif(destPath).then(exif => {
            if (exif && Object.keys(exif).length > 0) {
              query('UPDATE photos SET exif = ? WHERE id = ?', [JSON.stringify(exif), photoId]).catch(() => {});
            }
          }).catch(() => {});

          await query(
            'UPDATE galleries SET needs_rebuild = 1, updated_at = ? WHERE id = ?',
            [Date.now(), link.gallery_id],
          );

          // Business event — notifies editors
          const orgId = link.organization_id || link.studio_id;
          emit(EVENTS.PHOTO_UPLOADED, {
            studioId:         orgId,
            galleryId:        link.gallery_id,
            galleryTitle:     link.gallery_title,
            uploadLinkLabel:  link.label,
            photographerName: photographer?.name ?? null,
            photoCount:       1,
          });

        } finally {
          uploadFinished();
        }

        return res;
      },
    });

    _publicTusServer.set(key, server);
  }
  return _publicTusServer.get(key);
}
