// Copyright (c) 2026 Philippe Vollenweider
//
// This file is part of the GalleryPack commercial platform.
// This source code is proprietary and confidential.
// Use, reproduction, or distribution requires a valid commercial license.
// Unauthorized use is strictly prohibited.

// apps/api/src/services/tusService.js
//
// Builds a tus Server instance for a given gallery.
//
// Upload flow:
//   1. Client sends tus POST (create) with Upload-Metadata: filename, galleryId, userId
//   2. Server stores chunks under internal/tus/<galleryId>/
//   3. On complete (onUploadFinish):
//      a. Move file to private/<slug>/photos/<uuid>.<ext>
//      b. Run Sharp validation + SM thumbnail (same as multer pipeline)
//      c. INSERT into photos table (ON DUPLICATE KEY skips duplicates)
//      d. Enqueue MD thumbnail + prerender
//      e. Extract EXIF async
//      f. Mark gallery needs_rebuild
//
// The completed upload ID is the tus upload ID (UUID generated by @tus/server).
// The photo row ID is derived the same way as the multer flow: UUID = filename without ext.

import path              from 'node:path';
import fs                from 'node:fs';
import { randomUUID, createHash } from 'node:crypto';
import { createReadStream }       from 'node:fs';
import { Server }    from '@tus/server';
import { FileStore } from '@tus/file-store';
import { query }         from '../db/database.js';
import { SRC_ROOT, INTERNAL_ROOT } from '../../../../packages/engine/src/fs.js';
import { runSharp }      from './sharpProcess.js';
import { enqueueSm, enqueueMd, thumbPath, photoThumbnails } from './thumbnailService.js';
import { enqueuePrerender, uploadStarted, uploadFinished }  from './prerenderService.js';
import { extractExif }   from '../../../../packages/engine/src/exif.js';
import { audit, getUploadLinkByToken, getPhotographerByUploadLink } from '../db/helpers.js';
import { emit, EVENTS } from './events.js';
import { uploadLogger as log } from '../lib/logger.js';

// ── Content-hash helper ───────────────────────────────────────────────────────

function hashFile(filePath) {
  return new Promise((resolve, reject) => {
    const hash = createHash('sha256');
    createReadStream(filePath)
      .on('data', chunk => hash.update(chunk))
      .on('end',  ()    => resolve(hash.digest('hex')))
      .on('error', reject);
  });
}

// ── Storage quota helpers ─────────────────────────────────────────────────────

async function checkStorageQuota(studioId, additionalBytes) {
  const [rows] = await query(
    'SELECT storage_quota_bytes, storage_used_bytes FROM organizations WHERE id = ?', [studioId]
  );
  const studio = rows[0];
  if (!studio || studio.storage_quota_bytes === null) return;   // unlimited
  const projected = (Number(studio.storage_used_bytes) || 0) + additionalBytes;
  if (projected > Number(studio.storage_quota_bytes)) {
    const limitMB = Math.round(Number(studio.storage_quota_bytes) / 1_048_576);
    throw { status_code: 413, body: `Storage quota exceeded. Limit: ${limitMB} MB.` };
  }
}

async function incrementStorageUsed(studioId, bytes) {
  await query(
    'UPDATE organizations SET storage_used_bytes = GREATEST(0, storage_used_bytes + ?) WHERE id = ?',
    [bytes, studioId]
  );
}

export async function decrementStorageUsed(studioId, bytes) {
  await query(
    'UPDATE organizations SET storage_used_bytes = GREATEST(0, storage_used_bytes - ?) WHERE id = ?',
    [bytes, studioId]
  );
}
import {
  uploadTotal, uploadBytesTotal, uploadDuration, uploadFileSize,
  tusIncompleteUploads,
} from '../lib/metrics.js';

// ── Config ────────────────────────────────────────────────────────────────────

const MAX_FILE_SIZE_BYTES = (Number(process.env.UPLOAD_MAX_SIZE_MB) || 100) * 1024 * 1024;
const MAX_PHOTOS_PER_GALLERY = Number(process.env.GALLERY_MAX_PHOTOS) || 500;
const ALLOWED_EXTS = new Set(['.jpg', '.jpeg', '.png', '.tiff', '.tif', '.heic', '.heif', '.avif']);
const SUPPORTED_FORMATS = 'JPG, PNG, TIFF, HEIC, HEIF, AVIF';

// ── Helpers ───────────────────────────────────────────────────────────────────

// fs.rename(2) fails with EXDEV when source and destination are on different
// Docker bind mounts (internal vs private) even on the same physical disk.
// Fall back to copyFile + unlink in that case.
function moveFile(src, dest) {
  try {
    fs.renameSync(src, dest);
  } catch (err) {
    if (err.code !== 'EXDEV') throw err;
    fs.copyFileSync(src, dest);
    fs.unlinkSync(src);
  }
}

function photosDir(slug) {
  return path.join(SRC_ROOT, slug, 'photos');
}

function tusStoreDir() {
  return path.join(INTERNAL_ROOT, 'tus');
}

function decodeMetadata(metadata) {
  if (!metadata) return {};
  // @tus/server v2: metadata is already a parsed Record<string, string|null>
  if (typeof metadata === 'object') return metadata;
  // Legacy / raw Upload-Metadata header string (base64-encoded key-value pairs)
  const out = {};
  for (const pair of metadata.split(',')) {
    const [key, b64] = pair.trim().split(' ');
    if (key && b64) {
      try { out[key] = Buffer.from(b64, 'base64').toString('utf8'); } catch {}
    }
  }
  return out;
}

// ── Core post-upload pipeline ─────────────────────────────────────────────────
// Called by onUploadFinish. Mirrors the multer pipeline in photos.js exactly.

async function finaliseUpload({ upload, galleryId, userId, studioId, req }) {
  const meta = decodeMetadata(upload.metadata);
  const originalName = meta.filename || meta.name || path.basename(upload.id);
  const ext          = path.extname(originalName).toLowerCase();

  if (!ALLOWED_EXTS.has(ext)) {
    log.warn({ filename: originalName }, 'rejected — unsupported extension');
    return { ok: false, reason: `Unsupported format. Accepted: ${SUPPORTED_FORMATS}` };
  }

  // Resolve gallery slug
  // studioId may be null when superadmin uploads via platform root domain;
  // _studioId is resolved in onUploadCreate but use a safe fallback here too.
  const [gRows] = studioId
    ? await query('SELECT id, slug, organization_id FROM galleries WHERE id = ? AND organization_id = ?', [galleryId, studioId])
    : await query('SELECT id, slug, organization_id FROM galleries WHERE id = ?', [galleryId]);
  const gallery = gRows[0];
  if (!gallery) return { ok: false, reason: 'Gallery not found' };
  if (!studioId) studioId = gallery.organization_id;

  // Gallery quota
  const [countRows] = await query('SELECT COUNT(*) AS n FROM photos WHERE gallery_id = ?', [gallery.id]);
  if (Number(countRows[0].n) >= MAX_PHOTOS_PER_GALLERY) {
    return { ok: false, reason: `Gallery quota exceeded (max ${MAX_PHOTOS_PER_GALLERY} photos)` };
  }

  // tus stores the completed file at upload.storage.path
  const tusPath  = upload.storage?.path;
  if (!tusPath || !fs.existsSync(tusPath)) {
    return { ok: false, reason: 'Upload data file not found on disk' };
  }

  // Content-hash dedup: skip if identical file already in this gallery
  const contentHash = await hashFile(tusPath);
  const [dupRows] = await query(
    'SELECT id FROM photos WHERE gallery_id = ? AND content_hash = ? LIMIT 1',
    [gallery.id, contentHash],
  );
  if (dupRows[0]) {
    try { fs.unlinkSync(tusPath); } catch {}
    try { fs.unlinkSync(`${tusPath}.json`); } catch {}
    return { ok: true, duplicate: true };
  }

  const destDir  = photosDir(gallery.slug);
  fs.mkdirSync(destDir, { recursive: true });

  const photoId  = randomUUID();
  const destName = `${photoId}${ext}`;
  const destPath = path.join(destDir, destName);

  // Move tus completed file → photos directory
  moveFile(tusPath, destPath);

  // Remove tus info file (.json sidecar)
  try { fs.unlinkSync(`${tusPath}.json`); } catch {}

  // Sharp validation + SM thumbnail (same as multer pipeline)
  const smDest = thumbPath(photoId, 'sm');
  const mdDest = thumbPath(photoId, 'md');
  try {
    await runSharp({ op: 'validate-and-thumbs', srcPath: destPath, smPath: smDest, mdPath: mdDest });
  } catch (err) {
    log.error({ filename: originalName, err }, 'Sharp validation failed');
    return { ok: false, reason: `Format non reconnu ou fichier corrompu. Formats supportés : ${SUPPORTED_FORMATS}.` };
  }

  const sizeByte = fs.statSync(destPath).size;

  const [result] = await query(
    `INSERT INTO photos (id, gallery_id, filename, original_name, content_hash, size_bytes, status, uploaded_by_user_id)
     VALUES (?, ?, ?, ?, ?, ?, 'validated', ?)
     ON DUPLICATE KEY UPDATE size_bytes = VALUES(size_bytes), original_name = VALUES(original_name)`,
    [photoId, gallery.id, destName, originalName, contentHash, sizeByte, userId],
  );

  if (result.affectedRows === 2) {
    // Race-condition duplicate — clean up
    try { fs.unlinkSync(destPath); } catch {}
    try { fs.unlinkSync(thumbPath(photoId, 'sm')); } catch {}
    try { fs.unlinkSync(thumbPath(photoId, 'md')); } catch {}
    return { ok: true, duplicate: true };
  }

  enqueueSm(destPath, photoId);
  enqueueMd(destPath, photoId);
  enqueuePrerender(destPath, destName);

  extractExif(destPath).then(exif => {
    if (exif && Object.keys(exif).length > 0) {
      query('UPDATE photos SET exif = ? WHERE id = ?', [JSON.stringify(exif), photoId]).catch(() => {});
    }
  }).catch(() => {});

  await query(
    'UPDATE galleries SET needs_rebuild = 1, updated_at = ? WHERE id = ?',
    [Date.now(), gallery.id],
  );

  try { await audit(studioId, userId, 'photo.upload', 'gallery', gallery.id, { filename: destName, via: 'tus' }); } catch {}

  await incrementStorageUsed(studioId, sizeByte);
  uploadTotal.inc({ status: 'success' });
  uploadBytesTotal.inc({ status: 'success' }, sizeByte);
  uploadFileSize.observe(sizeByte);
  tusIncompleteUploads.dec();

  log.info({ photoId, gallery_id: gallery.id, filename: originalName, size_bytes: sizeByte }, 'upload finished');

  return { ok: true, photoId, file: destName, thumbnail: photoThumbnails(photoId) };
}

// ── Server factory ─────────────────────────────────────────────────────────────
// Returns a tus Server configured for the given studioId.
// Mount at /api/tus — galleryId comes from Upload-Metadata, not the URL.

export function createTusServer(studioId) {
  const datastore = new FileStore({ directory: tusStoreDir() });

  const server = new Server({
    path: '/api/tus',
    datastore,
    maxSize: MAX_FILE_SIZE_BYTES,
    generateUrl(_req, { id }) {
      const base = (process.env.BASE_URL || '').replace(/\/$/, '');
      return base ? `${base}/api/tus/${id}` : `/api/tus/${id}`;
    },
    // ── onCreate: validate gallery access before accepting any bytes ──────────
    // @tus/server v2: hooks receive (req: FetchRequest, upload) — no res param.
    // The original Express req is accessible via req.node?.req (srvx bridge).
    async onUploadCreate(req, upload) {
      const nodeReq   = req.node?.req ?? req;
      const meta      = decodeMetadata(upload.metadata);
      const galleryId = meta.galleryId;
      const userId    = nodeReq._tusUserId;      // set by tus.js before server.handle()

      if (!galleryId) {
        throw { status_code: 400, body: 'Missing galleryId in Upload-Metadata' };
      }

      // When studioId is null (superadmin via platform root domain), resolve the
      // gallery's org directly instead of filtering by organization_id.
      let effectiveStudioId = studioId;
      const [rows] = studioId
        ? await query('SELECT id, organization_id FROM galleries WHERE id = ? AND organization_id = ?', [galleryId, studioId])
        : await query('SELECT id, organization_id FROM galleries WHERE id = ?', [galleryId]);
      if (!rows[0]) {
        throw { status_code: 404, body: 'Gallery not found' };
      }
      if (!effectiveStudioId) effectiveStudioId = rows[0].organization_id;

      // Check storage quota before accepting any bytes
      if (upload.size > 0) {
        await checkStorageQuota(effectiveStudioId, upload.size);
      }

      upload._galleryId  = galleryId;
      upload._userId     = userId;
      upload._studioId   = effectiveStudioId;
      upload._createdAt  = Date.now();

      tusIncompleteUploads.inc();

      return {};
    },

    // ── onUploadFinish: run the full photo pipeline ───────────────────────────
    async onUploadFinish(req, upload) {
      const nodeReq   = req.node?.req ?? req;
      uploadStarted();
      const durationS = upload._createdAt ? (Date.now() - upload._createdAt) / 1000 : 0;
      try {
        const meta      = decodeMetadata(upload.metadata);
        const galleryId = meta.galleryId || upload._galleryId;
        const userId    = nodeReq._tusUserId  || upload._userId;

        const outcome = await finaliseUpload({
          upload,
          galleryId,
          userId,
          studioId: upload._studioId || studioId,
          req,
        });

        if (!outcome.ok) {
          uploadTotal.inc({ status: 'failed' });
          tusIncompleteUploads.dec();
          throw { status_code: 422, body: outcome.reason };
        }

        if (durationS > 0) uploadDuration.observe(durationS);
      } finally {
        uploadFinished();
      }

      return {};
    },
  });

  return server;
}

// ── Public tus server (upload-link / token flow) ───────────────────────────────
// Token is attached to req._uploadToken by the route middleware before calling server.handle().
// Photos are inserted with status 'approved' and auto-attributed to the linked photographer.

const _publicTusServer = new Map(); // one server (stateless — token validated per-request)

export function getPublicTusServer() {
  const key = '__public__';
  if (!_publicTusServer.has(key)) {
    const datastore = new FileStore({ directory: tusStoreDir() });

    const server = new Server({
      path:    '/upload/tus',
      datastore,
      maxSize: MAX_FILE_SIZE_BYTES,
      generateUrl(_req, { id }) {
        const base = (process.env.BASE_URL || '').replace(/\/$/, '');
        return base ? `${base}/upload/tus/${id}` : `/upload/tus/${id}`;
      },

      async onUploadCreate(req, upload) {
        const nodeReq = req.node?.req ?? req;
        const token   = nodeReq._uploadToken;
        if (!token) throw { status_code: 400, body: 'Missing upload token' };

        const link = await getUploadLinkByToken(token);
        if (!link) throw { status_code: 401, body: 'Invalid or expired upload link' };

        upload._link = link;
        return {};
      },

      async onUploadFinish(req, upload) {
        const link = upload._link;
        if (!link) throw { status_code: 401, body: 'Invalid or expired upload link' };

        uploadStarted();
        try {
          const meta         = decodeMetadata(upload.metadata);
          const originalName = meta.filename || meta.name || path.basename(upload.id);
          const ext          = path.extname(originalName).toLowerCase();

          if (!ALLOWED_EXTS.has(ext)) {
            throw { status_code: 422, body: `Unsupported format. Accepted: ${SUPPORTED_FORMATS}` };
          }

          // Quota
          const [countRows] = await query('SELECT COUNT(*) AS n FROM photos WHERE gallery_id = ?', [link.gallery_id]);
          if (Number(countRows[0].n) >= MAX_PHOTOS_PER_GALLERY) {
            throw { status_code: 422, body: `Gallery quota exceeded (max ${MAX_PHOTOS_PER_GALLERY} photos)` };
          }

          const tusPath = upload.storage?.path;
          if (!tusPath || !fs.existsSync(tusPath)) {
            throw { status_code: 500, body: 'Upload data file not found' };
          }

          // Content-hash dedup
          const contentHash = await hashFile(tusPath);
          const [dupRows] = await query(
            'SELECT id FROM photos WHERE gallery_id = ? AND content_hash = ? LIMIT 1',
            [link.gallery_id, contentHash],
          );
          if (dupRows[0]) {
            try { fs.unlinkSync(tusPath); } catch {}
            try { fs.unlinkSync(`${tusPath}.json`); } catch {}
            return res;
          }

          const destDir  = photosDir(link.gallery_slug);
          fs.mkdirSync(destDir, { recursive: true });

          const photoId  = randomUUID();
          const destName = `${photoId}${ext}`;
          const destPath = path.join(destDir, destName);

          moveFile(tusPath, destPath);
          try { fs.unlinkSync(`${tusPath}.json`); } catch {}

          const smDest = thumbPath(photoId, 'sm');
          const mdDest = thumbPath(photoId, 'md');
          try {
            await runSharp({ op: 'validate-and-thumbs', srcPath: destPath, smPath: smDest, mdPath: mdDest });
          } catch (err) {
            log.error({ filename: originalName, err }, 'Sharp validation failed (public)');
            throw { status_code: 422, body: `Format non reconnu. Formats supportés : ${SUPPORTED_FORMATS}.` };
          }

          const photographer = await getPhotographerByUploadLink(link.id);
          const sizeByte     = fs.statSync(destPath).size;

          const [result] = await query(
            `INSERT INTO photos (id, gallery_id, filename, original_name, content_hash, size_bytes, status, upload_link_id, photographer_id)
             VALUES (?, ?, ?, ?, ?, ?, 'approved', ?, ?)
             ON DUPLICATE KEY UPDATE
               size_bytes = VALUES(size_bytes),
               original_name = VALUES(original_name),
               photographer_id = VALUES(photographer_id)`,
            [photoId, link.gallery_id, destName, originalName, contentHash, sizeByte, link.id, photographer?.id ?? null],
          );

          if (result.affectedRows === 2) {
            try { fs.unlinkSync(destPath); } catch {}
            try { fs.unlinkSync(thumbPath(photoId, 'sm')); } catch {}
            try { fs.unlinkSync(thumbPath(photoId, 'md')); } catch {}
            return res;
          }

          enqueueSm(destPath, photoId);
          enqueueMd(destPath, photoId);
          enqueuePrerender(destPath, destName);

          extractExif(destPath).then(exif => {
            if (exif && Object.keys(exif).length > 0) {
              query('UPDATE photos SET exif = ? WHERE id = ?', [JSON.stringify(exif), photoId]).catch(() => {});
            }
          }).catch(() => {});

          await query(
            'UPDATE galleries SET needs_rebuild = 1, updated_at = ? WHERE id = ?',
            [Date.now(), link.gallery_id],
          );

          // Business event — notifies editors
          const orgId = link.organization_id;
          emit(EVENTS.PHOTO_UPLOADED, {
            studioId:         orgId,
            galleryId:        link.gallery_id,
            galleryTitle:     link.gallery_title,
            uploadLinkLabel:  link.label,
            photographerName: photographer?.name ?? null,
            photoCount:       1,
          });

        } finally {
          uploadFinished();
        }

        return {};
      },
    });

    _publicTusServer.set(key, server);
  }
  return _publicTusServer.get(key);
}
