apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gallerypack
  namespace: gallerypack
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - gallerypack.app
        - www.gallerypack.app
        - "*.gallerypack.app"
      secretName: gallerypack-wildcard-tls
  rules:
    - host: gallerypack.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 4000
    - host: www.gallerypack.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 4000
    - host: "*.gallerypack.app"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 4000
